[2024-06-25T17:02:18.772+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-25T17:02:18.793+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nasa_exo_data_to_s3.transform_nasa_exo_data manual__2024-06-25T17:02:07.120888+00:00 [queued]>
[2024-06-25T17:02:18.801+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nasa_exo_data_to_s3.transform_nasa_exo_data manual__2024-06-25T17:02:07.120888+00:00 [queued]>
[2024-06-25T17:02:18.821+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 4
[2024-06-25T17:02:18.886+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform_nasa_exo_data> on 2024-06-25 17:02:07.120888+00:00
[2024-06-25T17:02:18.892+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=434) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-25T17:02:18.894+0000] {standard_task_runner.py:63} INFO - Started process 436 to run task
[2024-06-25T17:02:18.894+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'nasa_exo_data_to_s3', 'transform_nasa_exo_data', 'manual__2024-06-25T17:02:07.120888+00:00', '--job-id', '96', '--raw', '--subdir', 'DAGS_FOLDER/etl_exo.py', '--cfg-path', '/tmp/tmpvyegfdkt']
[2024-06-25T17:02:18.895+0000] {standard_task_runner.py:91} INFO - Job 96: Subtask transform_nasa_exo_data
[2024-06-25T17:02:18.955+0000] {task_command.py:426} INFO - Running <TaskInstance: nasa_exo_data_to_s3.transform_nasa_exo_data manual__2024-06-25T17:02:07.120888+00:00 [running]> on host 95b3b965c5b1
[2024-06-25T17:02:19.060+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='test' AIRFLOW_CTX_DAG_ID='nasa_exo_data_to_s3' AIRFLOW_CTX_TASK_ID='transform_nasa_exo_data' AIRFLOW_CTX_EXECUTION_DATE='2024-06-25T17:02:07.120888+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-25T17:02:07.120888+00:00'
[2024-06-25T17:02:19.061+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-25T17:02:19.624+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-25T17:02:19.625+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-25T17:02:19.637+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=nasa_exo_data_to_s3, task_id=transform_nasa_exo_data, run_id=manual__2024-06-25T17:02:07.120888+00:00, execution_date=20240625T170207, start_date=20240625T170218, end_date=20240625T170219
[2024-06-25T17:02:19.910+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-25T17:02:19.919+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
