[2024-06-25T17:02:08.940+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-25T17:02:08.963+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nasa_exo_data_to_s3.fetch_nasa_exo_data manual__2024-06-25T17:02:07.120888+00:00 [queued]>
[2024-06-25T17:02:08.971+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nasa_exo_data_to_s3.fetch_nasa_exo_data manual__2024-06-25T17:02:07.120888+00:00 [queued]>
[2024-06-25T17:02:08.971+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-06-25T17:02:09.009+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): fetch_nasa_exo_data> on 2024-06-25 17:02:07.120888+00:00
[2024-06-25T17:02:09.015+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=431) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-25T17:02:09.016+0000] {standard_task_runner.py:63} INFO - Started process 433 to run task
[2024-06-25T17:02:09.016+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'nasa_exo_data_to_s3', 'fetch_nasa_exo_data', 'manual__2024-06-25T17:02:07.120888+00:00', '--job-id', '95', '--raw', '--subdir', 'DAGS_FOLDER/etl_exo.py', '--cfg-path', '/tmp/tmpjs_1z5_2']
[2024-06-25T17:02:09.018+0000] {standard_task_runner.py:91} INFO - Job 95: Subtask fetch_nasa_exo_data
[2024-06-25T17:02:09.074+0000] {task_command.py:426} INFO - Running <TaskInstance: nasa_exo_data_to_s3.fetch_nasa_exo_data manual__2024-06-25T17:02:07.120888+00:00 [running]> on host 95b3b965c5b1
[2024-06-25T17:02:09.185+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='test' AIRFLOW_CTX_DAG_ID='nasa_exo_data_to_s3' AIRFLOW_CTX_TASK_ID='fetch_nasa_exo_data' AIRFLOW_CTX_EXECUTION_DATE='2024-06-25T17:02:07.120888+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-25T17:02:07.120888+00:00'
[2024-06-25T17:02:09.187+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-25T17:02:15.962+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-25T17:02:15.963+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-25T17:02:15.972+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=nasa_exo_data_to_s3, task_id=fetch_nasa_exo_data, run_id=manual__2024-06-25T17:02:07.120888+00:00, execution_date=20240625T170207, start_date=20240625T170208, end_date=20240625T170215
[2024-06-25T17:02:16.147+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-25T17:02:16.166+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-06-25T17:02:16.191+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
