[2024-06-25T16:39:04.675+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-25T16:39:04.694+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nasa_neo_data_to_s3.transform_nasa_data manual__2024-06-25T16:39:00.833826+00:00 [queued]>
[2024-06-25T16:39:04.700+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nasa_neo_data_to_s3.transform_nasa_data manual__2024-06-25T16:39:00.833826+00:00 [queued]>
[2024-06-25T16:39:04.700+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 4
[2024-06-25T16:39:04.712+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform_nasa_data> on 2024-06-25 16:39:00.833826+00:00
[2024-06-25T16:39:04.718+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=89) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-25T16:39:04.719+0000] {standard_task_runner.py:63} INFO - Started process 91 to run task
[2024-06-25T16:39:04.719+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'nasa_neo_data_to_s3', 'transform_nasa_data', 'manual__2024-06-25T16:39:00.833826+00:00', '--job-id', '81', '--raw', '--subdir', 'DAGS_FOLDER/etl_neo.py', '--cfg-path', '/tmp/tmplewn0w5p']
[2024-06-25T16:39:04.720+0000] {standard_task_runner.py:91} INFO - Job 81: Subtask transform_nasa_data
[2024-06-25T16:39:04.755+0000] {task_command.py:426} INFO - Running <TaskInstance: nasa_neo_data_to_s3.transform_nasa_data manual__2024-06-25T16:39:00.833826+00:00 [running]> on host 95b3b965c5b1
[2024-06-25T16:39:04.820+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='test' AIRFLOW_CTX_DAG_ID='nasa_neo_data_to_s3' AIRFLOW_CTX_TASK_ID='transform_nasa_data' AIRFLOW_CTX_EXECUTION_DATE='2024-06-25T16:39:00.833826+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-25T16:39:00.833826+00:00'
[2024-06-25T16:39:04.821+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-25T16:39:04.862+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-25T16:39:04.862+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-25T16:39:04.869+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=nasa_neo_data_to_s3, task_id=transform_nasa_data, run_id=manual__2024-06-25T16:39:00.833826+00:00, execution_date=20240625T163900, start_date=20240625T163904, end_date=20240625T163904
[2024-06-25T16:39:04.892+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-25T16:39:04.911+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-06-25T16:39:04.912+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
